--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/dysphxria/.local/share/Steam/steamapps/workshop/content/431960/969834539/preview.jpg"

-- Special
background="#0F120D"
foreground="#c3c2c6"
cursor="#c3c2c6"

-- Colors
color0="#0F120D"
color1="#4A5333"
color2="#504E4E"
color3="#696669"
color4="#82816D"
color5="#797585"
color6="#837C8A"
color7="#c3c2c6"
color8="#88878a"
color9="#4A5333"
color10="#504E4E"
color11="#696669"
color12="#82816D"
color13="#797585"
color14="#837C8A"
color15="#c3c2c6"
