#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# General Settings
bspc config border_width         2
bspc config window_gap          2
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Window Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a nemo state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Polybar
polybar example &

# Wallpaper
setbg .wallpapers

# Low Battery
xfce4-power-manager &

ws-icon-0 = I;
ws-icon-1 = II;
ws-icon-2 = III;
ws-icon-3 = IV;

# Compositor
compton
