#! /bin/sh

#### AUTOSTART ####
sxhkd &
picom &
nitrogen --restore &
sh /home/art/.config/polybar/launch.sh 

bspc monitor -d I II III IV V VI VII VIII IX X

#### BSPWM configuration ####

bspc config border_width 5
bspc config window_gap 30
bspc config top_padding 60
bspc config left_padding 30
bspc config right_padding 30
bspc config border_radius 15

#get xrdb colors
highlight=$(xrdb -query | grep "*.highlight" | cut -f 2)
background=$(xrdb -query | grep "*.background-no-transparancy:" | cut -f 2)

bspc config focused_border_color "$highlight"
bspc config normal_border_color "$background"

bspc config focus_follows_pointer true
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
panel &
